### ISSUE TITLE
Precedence of selecting from multiple exchange protocols?

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#142]
I conceive that a few libraries may end up in a situation where more than one protocols are supported, for example,
- `__array_interface__`
- `__cuda_array_interface__`
- Python buffer protocol
- DLPack

Does it matter which protocol an array implementation should try first? Is it up to the library implementors?

**Comment by rgommers** [comment]
I think it's up to the library implementors, however there are a lot of subtleties so it may be useful to give some pointers.

Ideally people would use `from_dlpack` rather than `asarray`, which doesn't have this problem nor the problematic history of `asarray`.

In `asarray`, implementors should probably check `__dlpack_device__` first. They may then still decide to use `__cuda_array_interface__` first instead of `__dlpack__` if the device is CUDA for example. It shouldn't matter, if implemented correctly.

For libraries that support multiple devices, implementing all these protocols is a little tricky. For example, you then have to implement `__dir__` such that `hasattr(x, 'some_protocol') says `False` if that protocol does not support the device that `x` is on. The buffer protocol is particularly problematic, since you cannot hide it but it may still fail. I suspect that's the reason that deep learning frameworks don't implement the buffer protocol.

**Comment by leofang** [comment]
> Ideally people would use `from_dlpack` rather than `asarray`, which doesn't have this problem nor the problematic history of `asarray`.

Right, but AFAIK [we allow `asarray` to look up the DLPack support](https://data-apis.github.io/array-api/latest/API_specification/creation_functions.html?highlight=dlpack#asarray-obj-dtype-none-device-none-copy-none), so this complexity cannot be avoided. In particular, the `__dlpack__` method is going to be implemented in the "parent" objects such as `numpy.ndarray` and `cupy.ndarray`, so `{numpy, cupy}.asarray` may be impacted too. 

> The buffer protocol is particularly problematic, since you cannot hide it but it may still fail. 

This is part of the reason I am asking about this. For both NumPy and mpi4py, the buffer protocol is already supported and DLPack will be too, and for mpi4py I am considering to check the protocols in the following order:
```python
if (buffer protocol is supported):
    use buffer protocol
elif (__cuda_array_interface__ exists):
    use __cuda_array_interface__
elif (__dlpack__ exists):  # new
    use __dlpack__         # new  
else:
    raise
```
The pro on this order is that by the time `__dlpack__` is checked, CPU buffers are excluded and we only need to deal with CUDA/ROCm (unless there are some exotic, non-NumPy objects that are allocated on CPU but do not support buffer protocol, which I am unaware of so far, but even if it exists it's probably still fine).

**Comment by oleksandr-pavlyk** [comment]
Just a nit:

> unless there are some exotic, non-NumPy objects that are allocated on CPU but do not support buffer protocol

Python arbitrary precision integer comes to mind, but I do not think it affects your issue.

**Comment by rgommers** [comment]
> This is part of the reason I am asking about this. For both NumPy and mpi4py, the buffer protocol is already supported and DLPack will be too, and for mpi4py I am considering to check the protocols in the following order:

That sounds reasonable. Although you may consider checking for `__dlpack_device__` first, if it exists you can skip the non-device-relevant protocols.

> The pro on this order is that by the time `__dlpack__` is checked, CPU buffers are excluded

Not quite. Take a PyTorch tensor on CPU for example - it does not support the buffer protocol.

> which I am unaware of so far, but even if it exists it's probably still fine). I expect the same logic should work for cupy.asarray as well.

I agree, it will still be fine.

**Comment by leofang** [comment]
@rgommers Do you know off top of your head which is tried first in NumPy, buffer protocol or `__array_interface__`?

**Comment by rgommers** [comment]
The order is:
1. buffer protocol
2. `__array_interface__`
3. `__array__`

**Comment by leofang** [comment]
Thanks, Ralf! 

Note to self: it's done here https://github.com/numpy/numpy/blob/bb7a31a6a852ecc64d3f7cffb70121fc8bef20eb/numpy/core/src/multiarray/ctors.c#L1275

**Comment by leofang** [comment]
Given this doesn't seem to be an issue anymore, I'm closing it. Just FYI: In mpi4py we try in this order: buffer protocol -> DLPack -> CAI.
