### ISSUE TITLE
Why `arange` and not `range`?

### ISSUE THREAD

**Issue by SimonHeybrock** [data-apis/array-api#284]
The latest API specification defines `max`, i.e., compared to `numpy.amax` the "a" prefix is dropped. I had always assumed the "a" is historic &mdash; from times when more people used `from module import *` &mdash; to avoid clashes with the builtins.

Therefore I wonder: Why is the "a" prefix not dropped in `arange`? Is it an oversight or intentional?

**Comment by kgryte** [comment]
For the API comparison which helped motivate the continued use of `arange`, instead of `range`, see the API comparison [data](https://github.com/data-apis/array-api-comparison/blob/a2fdc6b7a7ac4728519785550c6cf25a7ca69973/signatures/creation/arange.md).

In this case, we opted for sticking with convention and, thus, the naming is intentional. As this question is answered, will go ahead and close out.
