### ISSUE TITLE
Discussion: DLPack requires 256B alignment of data pointers

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api#293]
Recently [we found](https://github.com/rapidsai/cudf/issues/9389) that DLPack has this requirement noted in the header:
https://github.com/dmlc/dlpack/blob/a02bce20e2dfa0044b9b2ef438e8eaa7b0f95e96/include/dlpack/dlpack.h#L139-L141. Would this be an issue for all adopting libraries? As far as I know, CuPy doesn't do any alignment check and take the pointer (`DLTensor.data`) as is, and IIRC quite a few other libraries are also doing this. 

cc: @seberg @rgommers @tqchen @kmaehashi @oleksandr-pavlyk @jakirkham @edloper @szha

**Comment by rgommers** [comment]
> Now, I don't know what their allocation strategy is, so I don't know whether they even guarantee itemsize-alignment for `complex128` on 32bit platforms.

PyTorch doesn't support 32-bit platforms AFAIK. It's not impossible that there's a custom armv7 mobile build or some such thing floating around, but certainly there's no wheels, conda packages or CI for 32-bit platforms.

> As for their `fromDLPack` function just below: It doesn't even _check_ if `byte_offset != 0`, so maybe we should just always keep it 0 and and not think about it for CPU data... 

This may be true for other libraries as well. It seems clear from the above this discussion that there's a desire to have alignment better specified and in the future enforced. It looks to me like this will need gradual evolution:

1. Document better in `dlpack.h` how to deal with alignment. I opened a PR for that: https://github.com/dmlc/dlpack/pull/83
2. Fix the consumer functions (`from_dlpack`) in all known implementations to correctly handle byte offsets, and give warnings for non-aligned input.
3. Wait at least one release before adjusting the producer functions (`__dlpack__` / `to_dlpack`) to have an aligned base pointer and nonzero `byte_offset`.
4. Wait another period of time, then give hard errors in the consumer function.

**Comment by rgommers** [comment]
> > The use of `byte_offset` for opaque data pointers is interesting. Do you suggest to also use it for non-opaque data pointers to enforce/allow a bigger allocation alignment guarantee then data alignment? Is that useful, scanning that initial link @leofang posted sounded like it might be?
> 
> Yes this would be really helpful. Knowing the base allocation pointer, offset, and alignment often allows for much more efficient code.

It looks like the answer changed here (or at least my reading of it): (xref https://github.com/dmlc/dlpack/pull/83#issuecomment-964382536). Let me try to summarize:

- Not all libraries have aligned allocators, certainly not to 256 bytes.
- There is no place currently for the producer to put information about the alignment of the data in the dlpack capsule it is exporting. It cannot be added until there is a version attribute and a way to extend DLPack (separate issue that needs tackling, state of today is that that doesn't exist).
- The consumer cannot know whether it is safe to read memory between `data` and `data + byte_offset`. Hence aligned loads are not possible today unless `data + byte_offset` happens to be aligned already. 
- And no aligned loads for opaque data pointers may be possible at all, unless there's a device/language guarantee about this (quoting @seberg: _"Is a 256 byte alignment guaranteed for any possible opaque pointer?! Because if it is not, I don't see any point for this guarantee"_). It is not documented for which devices this is the case.

These are the options:
1. **A1: required alignment**. Require the `data` pointer to always be aligned (using nonzero `byte_offset`), and do the gradual evolution plan in my comment above.
2. **A2: no alignment**. remove the allocation requirement completely from `dlpack.h`. no library needs to make any changes (except if current handling of `byte_offset` is buggy, like @seberg pointed out for PyTorch). NumPy and other new implementers then just use `byte_offset=0` always (easiest), and we're done.
3. **A3: optional alignment**. Do not _require_ alignment, but add a way to communicate from the producer to the consumer what the alignment of the data is.

The current status is that the fine print in `dlpack.h` requires alignment (option A1), but no one adheres to it or enforces it. This state is not very useful: it requires a >1 year evolution plan, and apparently there's no gain because of the third bullet above. So it looks like the best choices are either A2 or A3. A3 seems strictly better than A2, _and most of the work it requires (versioning/extensibility) is work we wanted to do for other reasons already_.

So here's a new proposal:
- Decide that the long-term desired state is _A3: optional alignment_
- NumPy and other new implementers to do whatever is simplest, i.e. to use `byte_offset = 0` and `data` pointing to the first element in memory.
- Update the comment in `dlpack.h` about this topic to reflect: current state, desired future state, and a link to a new issue on the DLPack repo with more info (outcome of this discussion to be summarized on that issue).

**Comment by kkraus14** [comment]
If we're making longer term changes surrounding optional alignment in A3, it would be nice to have optional padding as well so that we know how many bytes past `data + byte_offset + size` can be safely read to allow further optimization as well.
