### ISSUE TITLE
Add `exp10` function to the standard

### ISSUE THREAD

**Issue by steff456** [data-apis/array-api#592]
This RFC requests to include a new API in the array API specification for the purpose of computing the base-10 exponential.

## Overview

The Array API specification currently includes `log10`, `exp`, and `pow`, but does not include the IEEE 754 function `exp10`. Would be nice to add for completeness.

- log10: <https://github.com/data-apis/array-api/blob/3d918783ac7f11cb5b31681b2badddeca81dc71e/src/array_api_stubs/_2022_12/elementwise_functions.py#L1494>

While this can currently be achieved now by using `pow`, `exp10` is commonly implemented as a slightly more ergonomic perf path.

## Prior art

- SciPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.exp10.html
- IEEE 754

## Proposal:

```python
def exp10(x: array, /) -> array
```

cc @kgryte

**Comment by rgommers** [comment]
I think this maybe makes some sense for symmetry reasons (since we have `log10`), however it's (a) low-prio, and (b) blocked by lack of support in all libraries and C99.

I'd suggest closing this, since there's not much of an upside in keeping it open. If in 1-2 years from now there is real user demand and there are implementations in libraries, it can always be reopened.

**Comment by rgommers** [comment]
No further comments, so I'll close this. We can revisit in the future if needed.
