### ISSUE TITLE
Better `str` array and dtype ?

### ISSUE THREAD

**Issue by Conchylicultor** [data-apis/array-api#611]
Currently, `str` arrays in numpy feels quite unintuitive and always require some special cases.

I feel it would be simpler if str arrays were matching TensorFlow `tf.string` array behavior more closely. More specifically, `tf.string` tensors are similar to `dtype=object`, but only have `str` / `bytes` values rather than arbitrary object.

For example:

* Currently, how str `dtype` works is quite confusing:

  ```python
  x = np.array(['aaaaa', 'b'], dtype=np.str_)
  assert x.dtype == np.str_  # <<< Raise an error. What ?
  ```

  There's no obvious way to check that the array is a `str` array. Only weird hacks like: `a.dtype.char == 'U'`

* A new `dype('<U11')` is generated using the longest string in the array. This waste **a LOT** of space as all str are padded to the longest one.

In 99% of case, this behavior just makes things much harder to use `str` array.

## Proposal

Have 2 dtypes `np.str` and `np.bytes`. Internally, those would act similarly to `dtype=object` but only accept respectively `str` / `bytes` values.

```python
x = np.array(['aaaaa', 'b'], dtype=np.str)
assert x.dtype  == np.str  # No more padding / dynamic type
```

This is how TF currently works (with `tf.string` would be similar to `np.bytes`).

```python
x = tf.constant([b'aaaaa', b'b'], dtype=tf.string)
assert x.dtype  == tf.string
```

**Comment by rgommers** [comment]
Hi @Conchylicultor, string dtypes are out of scope for this standard, because they're not implemented by most array libraries. We don't cover those at all. That said, I completely agree with your assessment of the NumPy string dtypes being not so great. At the moment a bunch of work is happening in https://github.com/numpy/numpy-user-dtypes to create a new variable-length string NumPy dtype that will work a lot more smoothly. It already is in a working state, and initial integration with Pandas worked well. You may want to check in there.

**Comment by rgommers** [comment]
Hi @Conchylicultor, I think the question has been answered and since this is out of scope for the array API standard, I'll close the issue. Happy to discuss more though if needed.
