### ISSUE TITLE
Clarification needed for documentation of ceil, trunc, floor

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [data-apis/array-api#657]
Spec for [`ceil`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.ceil.html), [`floor`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.floor.html), and [`trunc`](https://data-apis.org/array-api/latest/API_specification/generated/array_api.trunc.html) need to be clarified to specify its behavior for input arrays of integral types. 

The current reading may be interpreted to mean that `xp.floor(int_array)` should return array of integral type, which is inconsistent with `numpy`'s behavior where returned array is of a floating-point type. 

The cause for this misinterpretation is the verbiage for special case:

> If `x_i` is already integer-valued, the result is `x_i`.

keep in mind the usage line 

> Rounds each element `x_i` of the input array `x` to the smallest integer-valued number that is not less than `x_i`.

In both these cases, I think the spec means to say "integer-valued floating-point number".

It would be awesome to clarify this aspect.

**Comment by kgryte** [comment]
@oleksandr-pavlyk Thanks for raising this. The spec, as written, is correct in its intent. Namely, that, for the returned array, the array should be have the same data type as the input array. This is also true as implemented in the [array-api-compat](https://github.com/data-apis/array-api-compat/blob/dab6775d3831eca0512a1b4ef6e5f8a439574cda/array_api_compat/common/_aliases.py#L425) library.

In short, if a user provides an array having an integral type to a rounding function, the operation should, for all intents and purposes, be a no-op. Using rounding functions to force a floating-point array does not seem optimal and deviating from NumPy behavior in its main namespace was intentional at the time of writing the spec.

**Comment by oleksandr-pavlyk** [comment]
Thank you for confirming this @kgryte . I am closing the issue.
