### ISSUE TITLE
result_type for explicit promotion

### ISSUE THREAD

**Issue by ezyang** [data-apis/array-api#91]
Currently the recommendation for code that needs to promote is:

> Therefore we had to make the choice to leave the rules for “mixed kind dtype casting” undefined - when users want to write portable code, they should avoid this situation or use explicit casts to obtain the same results from different array libraries. 

In eager mode frameworks, making operations portable in this way also can result in extra memory usage, as you have to first do the cast, and then do the operation, whereas the cast might have been fused internally in the framework. 

However, it's not clear how important this actually is in practice, since at least in PyTorch, a lot promotion *is* in fact implemented by first doing a cast and then doing a normal operation (instead of implementing quadratically many kernels). I don't know off the top of my head which operations this would be relevant for.

**Comment by rgommers** [comment]
Thanks @ezyang, good point about performance in eager mode. I'd be inclined to say the damage is limited enough that it's a cost worth paying (for now at least). And if someone finds it to be a bottleneck, that'd be (a) good data, and (b) likely possible to work around with a `try-except` (only do the explicit cast if mixed int-float raises).

I just tested TensorFlow 2.4.0, and was surprised that `tf.experimental.numpy` doesn't raise there (regular TF does), it does the same aggressive upcasting to `float64` as numpy does it looks like. CuPy also follows NumPy, while JAX does do mixed operations but is a bit better about keeping `float32`. PyTorch is also implementing mixed int-float casting, and IIRC will do the same as JAX (e.g. `int32 + float32 -> float32` rather than `float64`). So it could well be that when the standard is implemented, there's only subtle differences left. Those are still hard to reconcile, but may be okay-ish to ignore for portability if the application is fine with float32 precision-wise.

`result_type` also came up in gh-14 and gh-43; gh-99 adds it to the API spec.

**Comment by rgommers** [comment]
`result_type` was added, closing
